### PR TITLE
Fixed typo in label

### PR DESCRIPTION
**Pull request by ametad**
Hi Mattias,

I found a typo and now I try to give you this as a 'pull request'. But is this the right way to do this? I am a little confused because of all the buttons I can press here in Github... But hopefully this works out correctly... or I'll will try to do this another way.

Regards,
Anne (Webplaats)

### CODE REVIEW

**Comment by ametad** [comment]
Not sure why, but it looks like I accidentally did append my commit to the last commit of the original project...?!

**Comment by hambern** [comment]
Not really sure how to do this. Has made the changes though ;)

**Comment by ametad** [comment]
Well that is the whole idea in the end ;-) That's a good thing. Perhaps for now ignore this request and I will come up with a new and different one; including dutch translations.

**Comment by ametad** [comment]
May I just make pull requests to you master branch? Or do you perhaps like them to go to development branch?

**Comment by hambern** [comment]
Do whatever works basically. Trying to learn this thing right now ;)

**Pull request closed without merging**
